### ISSUE TITLE
Bot no longer works without specified db

### ISSUE THREAD

**Issue by dabukalam** [nuxeh/url-bot-rs#12]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: posts"))', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by nuxeh** [comment]
How did you run the command?

**Comment by dabukalam** [comment]
with no arguments

**Comment by polyzen** [comment]
Can confirm that currently a DB is mandatory.
