### ISSUE TITLE
Look at fetching filenames somehow for pages without titles

### ISSUE THREAD

**Issue by dabukalam** [nuxeh/url-bot-rs#15]
Example would be just a png file or even an audio file, which wouldn't have a <title />

**Comment by nuxeh** [comment]
I was thinking it could be interesting to verify the content somehow...
1. make sure it gets a valid http response
2. validate the data... somehow detect the filetype/file header/MIME?
then say "[image-png]" or something... what do you think?

**Comment by nuxeh** [comment]
Looks to me that the `mime` crate creates types to represent MIME information, and convert between MIME strings and rust types.

There is on the other hand, this: https://crates.io/crates/immeta or this: https://crates.io/crates/image

Might be nice to post the image dimensions, or other metadata.

**Comment by nuxeh** [comment]
Looks like you do get content headers with the HTTP 200 response, though, try `curl -v`. Which means you could tidily do some matching that using the `mime` crate. Maybe then if it's an image type supported by the `immeta` or `image` crates, get any further metadata desired for images.

Using `mime` would give a tidy option to be able to post the content type for all manner of things, if no title is available, simply and cheaply. I imagine the `image` crate could be a relatively heavy dependency, possibly.

**Comment by nuxeh** [comment]
#35 is a step towards something along these lines.

**Comment by nuxeh** [comment]
We now have image metadata extraction merged, could additionally look into audio and video metadata, have opened a new issue for this, #61
