### ISSUE TITLE
Some YouTube links generate unhelpful title summaries

### ISSUE THREAD

**Issue by rjek** [nuxeh/url-bot-rs#323]
Some YouTube links are fetched simply as "YouTube", visiting them in a browser appears to show the title bar being lazily updated to appropriate title.

```
[10:10:29] <neill> https://www.youtube.com/watch?v=XtvvzxET1GI
[10:10:29] <earlbot> ⤷ YouTube
```

**Comment by nuxeh** [comment]
Hi @rjek, this is known about, and can be mitigated for now by running #319 

In the longer term, the plan is to use the YouTube API to get titles for YouTube, since it's quite unclear to me what YouTube is doing which means it's not giving out full titles.

**Comment by rjek** [comment]
Ta, confirm this hack fixes our immediate problem.

**Comment by nuxeh** [comment]
Good to know :)
