### ISSUE TITLE
Occasional timeouts

### ISSUE THREAD

**Issue by nuxeh** [nuxeh/url-bot-rs#36]
We've noticed some occasional timeouts on links that are otherwise fine recently, it seems since the `reqwest` refactor... something like this:

```
RESOLVE https://github.com/nuxeh/url-bot-rs/commit/6f83f1a0872f884364fa45badd80830d87d6a028
ERROR Inner { kind: Io(Custom { kind: WouldBlock, error: StringError("timed out") }), url: Some("https://github.com/nuxeh/url-bot-rs/commit/6f83f1a0872f884364fa45badd80830d87d6a028") }
```

**Comment by panicbit** [comment]
This is probably due to the [I/O timeout here](https://github.com/nuxeh/url-bot-rs/blob/682049755133c5d185f130ba0f5c91e261934d24/src/http.rs#L14).
We could try raising it a little bit.

**Comment by nuxeh** [comment]
A couple more, for the record.

```
ERROR Inner { kind: Io(Custom { kind: WouldBlock, error: StringError("timed out") }), url: Some("http://google.com/") }
ERROR Inner { kind: Io(Custom { kind: WouldBlock, error: StringError("timed out") }), url: Some("https://metrouk2.files.wordpress.com/2018/08/theresa-may-8c38.gif") }
```

**Comment by nuxeh** [comment]
Raising the timeout to 10s seems to have mitigated this for now.
