### ISSUE TITLE
No ping response

### ISSUE THREAD

**Issue by nuxeh** [nuxeh/url-bot-rs#43]
`IRC client error: connection reset: no ping response`

**Comment by nuxeh** [comment]
Maybe this could be mitigated by updating https://github.com/nuxeh/url-bot-rs/blob/8f1593ecc035f3cc5910a99cd1e44f54e9edddf6/example.config.toml#L17

**Comment by polyzen** [comment]
I've seen projects use `8s`--`300s` here. Haven't had to manually boot the bot back up since changing this to `300s` >.> (aside from when a bunch of users timed out at once recently).
