### ISSUE TITLE
error: Could not compile `http`

### ISSUE THREAD

**Issue by mandala-mbwa** [nuxeh/url-bot-rs#48]
`cargo build --verbose`

```       ...
       Fresh uuid v0.7.1
       Fresh tokio-io v0.1.9
   Compiling http v0.1.13
     Running `rustc --crate-name http /home/mandala/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.13/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=5cfda549ba91067c -C extra-filename=-5cfda549ba91067c --out-dir /home/mandala/url-bot-rs/target/debug/deps -L dependency=/home/mandala/url-bot-rs/target/debug/deps --extern bytes=/home/mandala/url-bot-rs/target/debug/deps/libbytes-b70a93e3d6941dcd.rlib --extern fnv=/home/mandala/url-bot-rs/target/debug/deps/libfnv-dada980a2fbe3615.rlib --extern itoa=/home/mandala/url-bot-rs/target/debug/deps/libitoa-8bfc3b49ec34e3b3.rlib --cap-lints allow`
error: Could not compile `http`.

Caused by:
  process didn't exit successfully: `rustc --crate-name http /home/mandala/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.13/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=5cfda549ba91067c -C extra-filename=-5cfda549ba91067c --out-dir /home/mandala/url-bot-rs/target/debug/deps -L dependency=/home/mandala/url-bot-rs/target/debug/deps --extern bytes=/home/mandala/url-bot-rs/target/debug/deps/libbytes-b70a93e3d6941dcd.rlib --extern fnv=/home/mandala/url-bot-rs/target/debug/deps/libfnv-dada980a2fbe3615.rlib --extern itoa=/home/mandala/url-bot-rs/target/debug/deps/libitoa-8bfc3b49ec34e3b3.rlib --cap-lints allow` (signal: 9, SIGKILL: kill)
```
```
$ cargo -V
cargo 1.29.0 (524a578d7 2018-08-05
```
Ubuntu 18.10 (beta), Debian Sid

**Comment by nuxeh** [comment]
Hi, it looks like `rustc` was killed with SIGKILL. Did you kill the process, or run out of memory?

What revision are you building?

There are automated tests running in travis, which are passing, and it builds locally for me, so I wouldn't expect build issues.

**Comment by mandala-mbwa** [comment]
Hello!

Indeed, I just forgot about the memory :). I upgraded to 8 GB, the build ended successfully.

How much memory do you recommend for a successful build?

**Comment by nuxeh** [comment]
I'm not sure what a recommended requirement for memory size would be for build. This is a relatively small rust project, so similar if not less than most rust projects. Also, it's currently built regularly on two separate machines with 1GB of system RAM.

I just checked how much memory it uses during a build. Sadly the rust toolchain doesn't work inside `valgrid` with `massif`, but running a full clean build with GNU `time` on Linux produces the following:

```
$ command time -v cargo build
   ...
   Compiling url-bot v0.1.0 (file:///home/ed/git/url-bot-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 28s
	Command being timed: "cargo build"
	User time (seconds): 501.44
	System time (seconds): 15.58
	Percent of CPU this job got: 348%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:28.50
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 615656
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 9
	Minor (reclaiming a frame) page faults: 2923405
	Voluntary context switches: 15112
	Involuntary context switches: 86462
	Swaps: 0
	File system inputs: 3776
	File system outputs: 1863632
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
`Maximum resident set size (kbytes): 615656` suggests it used a peak of around 600MB.

This kind of memory usage shouldn't really be a problem, so i assume there's something else going on, for example you might be running stuff in the background with high memory usage - web browser perhaps. Also the fact that you possibly had an out of memory (OOM) kill might be the case that your system's swap is turned off, for example.

**Comment by mandala-mbwa** [comment]
Thanks for the detailed answer.

I first used a clean instance in the cloud with only 512 MB of memory, and forgot to enable swap. Then I turned on 8 GB on emotions, cursing myself for inattention :).

I think with a little swap, I will not have problems in the future on the initial configuration.

Thanks again.

**Comment by nuxeh** [comment]
No problem :) glad you got it sorted!
