### ISSUE TITLE
Deduplication of urls within a message

### ISSUE THREAD

**Issue by benjamb** [nuxeh/url-bot-rs#57]
For cases when people are very excited about something
```
09:55 < fooser> https://i.imgur.com/MU2peAR.gifv https://i.imgur.com/MU2peAR.gifv https://i.imgur.com/MU2peAR.gifv
09:56 < url-bot> ⤷ Imgur
09:56 < url-bot> ⤷ Imgur → Thu Oct 18 08:55:59 2018 fooser (#foo)
09:56 < url-bot> ⤷ Imgur → Thu Oct 18 08:55:59 2018 fooser (#foo)
```
Ideally filters regardless of where in the message the duplicates are.

**Comment by nuxeh** [comment]
Could potentially use a [HashSet](https://doc.rust-lang.org/std/collections/struct.HashSet.html) for this?

**Comment by nuxeh** [comment]
https://docs.rs/itertools/0.6.5/itertools/trait.Itertools.html#method.dedup

**Comment by nuxeh** [comment]
Thanks @mgsh for the fix!
