### ISSUE TITLE
Vice

### ISSUE THREAD

**Issue by nuxeh** [nuxeh/url-bot-rs#95]
`ERROR ErrorMessage { msg: "failed to parse title" }` for:

https://www.vice.com/en_uk/article/zmaedw/i-pretended-to-be-a-young-joseph-stalin-on-tinder-and-it-went-weirdly-well?utm_source=vicefbuk&fbclid=IwAR0zpucOU2-CV6cMHsrF05NqQUqbjNIeai24XvlZjGJVZWB9xjQOjivPbrM

**Comment by polyzen** [comment]
FWIW this also fails with Limnoria's `titleSnarfer`.

**Comment by nuxeh** [comment]
This is a bit weird, it works now, and i've tried as far back in the history as was easy to test, to start a bisect, but it works going back way into last year. Anyway, this one seems to be fixed, could be that they changed the page server side.
